# Generated by Django 2.2.3 on 2020-08-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieShortComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_comments', models.TextField(blank=True, max_length=5000, null=True, verbose_name='短评')),
                ('star', models.CharField(max_length=3, verbose_name='星级')),
                ('comment_time', models.CharField(max_length=20, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '短评数据',
                'verbose_name_plural': '电影短评数据列表',
                'db_table': 'movie_short_comments',
            },
        ),
    ]
