# Generated by Django 2.2.3 on 2020-08-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_douban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieshortcomments',
            old_name='short_comments',
            new_name='short_comment',
        ),
        migrations.AlterField(
            model_name='movieshortcomments',
            name='comment_time',
            field=models.CharField(max_length=50, verbose_name='评论时间'),
        ),
    ]
